apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: pless-me
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
#  - image: jcr.bongladesch.com/docker-dev/pless-me
  - image: ingress-nginx-svc.kube-system.svc.bongladesch.com/docker-dev/pless-me
    context: .
#    docker:
#      dockerfile: src/main/docker/Dockerfile
    kaniko:
      dockerfile: src/main/docker/Dockerfile
      skipTLS: true
  cluster:
    namespace: build
    pullSecretName: regcred-dev
deploy:
  kubectl:
    manifests:
    - src/main/kubernetes/*.yaml
