FROM jcr.bongladesch.com/docker/stack/buildpipeline:0.1.0

COPY ./build.gradle /home/quarkus/build.gradle
COPY ./settings.gradle /home/quarkus/settings.gradle
COPY ./gradle.properties /home/quarkus/gradle.properties
COPY ./src/ /home/quarkus/src

CMD ["gradle", "quarkusDev"]