apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: keycloak
    group: plessme
  name: plessme-keycloak-cm
  namespace: dev
data:
  KEYCLOAK_USER: keycloak
  KEYCLOAK_PASSWORD: keycloak
  PROXY_ADDRESS_FORWARDING: "true"
  DB_VENDOR: postgres
  DB_ADDR: plessme-postgres-svc
  DB_PORT: "5432"
  DB_DATABASE: keycloak
  DB_USER: keycloak
  DB_PASSWORD: keycloak
