package com.bongladesch.plessme.users.adapter.keycloak;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

import com.bongladesch.plessme.common.usecase.ILogger;
import com.bongladesch.plessme.users.entity.User;
import com.bongladesch.plessme.users.entity.User.UserBuilder;
import com.bongladesch.plessme.users.usecase.IIdentityProvider;

import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.eclipse.microprofile.rest.client.inject.RestClient;

/**
 * KeycloakIdentityProvider is a Keycloak identity provider
 * implementation of the plessme identity provider interface.
 */
@ApplicationScoped
public class KeycloakIdentityProvider implements IIdentityProvider {

    /**
     * Keycloak API rest client implementation is injected by CDI.
     * Class fields must be package private due to implementation quarkus.
     */
    @Inject
    @RestClient
    KeycloakRestClient keycloakRestClient;

    @Inject
    @ConfigProperty(name = "plessme.keycloak.realm")
    String realm;

    @Inject
    @ConfigProperty(name = "plessme.keycloak.client.id") 
    String clientId;

    @Inject
    @ConfigProperty(name = "plessme.keycloak.client.secret")
    String clientSecret;

    @Inject
    ILogger logger;

    /**
     * Create an enabled user in Keycloak for OAuth2 implementation by given user data.
     * @param user User object to create a Keycloak user from.
     * @return The id of the user generated by Keycloak.
     */
    @Override
    public User createUser(User user) {
        logger.debug("Request OIDC access token from Keycloak to create user with email: " + user.getEmail());
        KeycloakTokenResponse tokenResponse = keycloakRestClient.getToken(realm, "client_credentials", clientId, clientSecret);
        logger.debug("Create user from user data in Keycloak");
        keycloakRestClient.createUser(realm, createAuthHeader(tokenResponse), new KeycloakUserRepresentation(user));
        logger.debug("Request new users ID and creation timestamp from Keycloak and add to new user object for return");
        KeycloakUserRepresentation keycloakUser = keycloakRestClient.getUserByEmail(realm, createAuthHeader(tokenResponse), user.getEmail())[0];
        UserBuilder builder = new UserBuilder().
            id(keycloakUser.id).
            created(keycloakUser.createdTimestamp).
            email(user.getEmail()).
            password(user.getPassword()).
            firstName(user.getFirstName()).
            lastName(user.getLastName());
        return builder.build();
    }

    /**
     * CreateAuthHeader creates the value of a bearer token
     * authorization request header from keycloak token response object.
     * @param response The token response object from keycloak.
     * @return The authorization header value for bearer tokens.
     */
    private String createAuthHeader(KeycloakTokenResponse response) {
        return "Bearer " + response.access_token;
    }
}