apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: mongo-express
    group: plessme
  name: plessme-mongo-express-cm
  namespace: dev
data:
  ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
  ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
  ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
  ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
  ME_CONFIG_MONGODB_SERVER: plessme-mongo-svc
  ME_CONFIG_MONGODB_PORT: "27017"
  ME_CONFIG_SITE_BASEURL: /mongo