apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    group: plessme
  name: plessme-postgres-svc
  namespace: dev
spec:
  selector:
    app: postgres
    group: plessme
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432