apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: postgres
    group: plessme
  name: plessme-postgres-cm
  namespace: dev
data:
  POSTGRES_DB: keycloak
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: keycloak
  PGDATA: /var/lib/postgresql/data