apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres
    group: plessme
  name: plessme-postgres-dpl
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      group: plessme
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
        group: plessme
    spec:
      containers:
      - image: postgres:12.2
        name: postgres
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
          requests:
            cpu: "0.1"
            memory: 124Mi
        envFrom:
        - configMapRef:
            name: plessme-postgres-cm
        ports:
        - name: jdbc
          containerPort: 5432
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            subPath: postgres
            name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: dev-pvc
